language: android
jdk: oraclejdk7

android:
  components:
    - build-tools-19.0.1

script:
  # Use `TERM=dumb` to simplify console output
  - TERM=dumb ./gradlew assembleDebug -PdisablePreDex